version: 2
updates:
  # Konfigurasi untuk memeriksa pembaruan dependensi npm (package.json)
  - package-ecosystem: "npm"
    # Direktori tempat package.json berada (di root)
    directory: "/"
    # Jadwal seberapa sering dependabot akan memeriksa pembaruan
    schedule:
      interval: "weekly" # Pilihan lain: "daily" atau "monthly"
    
    # Batasi jumlah PR terbuka agar tidak terlalu banyak
    open-pull-requests-limit: 10
    
    # Commit message prefix untuk npm
    commit-message:
      prefix: "chore"
      include: "scope"
    
    # Opsi lain yang bisa berguna:
    # labels:
    #   - "dependencies"

  # Konfigurasi untuk memperbarui Actions yang digunakan di GitHub Workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
